// ========== MOVIE DATA ==========
const MOVIES = {
  'body-horror': [
    { year: 1980, title_cn: '灵魂大搜索', title_en: 'Altered States', country: '美国', desc: '科学家用致幻剂探索意识，身体发生退化变异', rating: '7.1', douban: 'https://movie.douban.com/subject/1293762/', poster: 'https://image.tmdb.org/t/p/w500/fsoaPN5SWYgZ4B7GG9nRNj33so.jpg' },
    { year: 1981, title_cn: '美国狼人在伦敦', title_en: 'An American Werewolf in London', country: '美国/英国', desc: '美国青年在英国被狼人咬伤后逐渐变身', rating: '7.3', douban: 'https://movie.douban.com/subject/1295077/', poster: 'https://image.tmdb.org/t/p/w500/hVEqUASJmCQaolkKFEySCHZ8uKG.jpg' },
    { year: 1982, title_cn: '怪形', title_en: 'The Thing', country: '美国', desc: '南极科考队遭遇能模仿任何生物的外星怪物', rating: '8.2', douban: 'https://movie.douban.com/subject/1296794/', poster: 'https://image.tmdb.org/t/p/w500/tzGY49kseSE9QAKk47uuDGwnSCu.jpg' },
    { year: 1983, title_cn: '录影带谋杀案', title_en: 'Videodrome', country: '加拿大', desc: '电视台经理沉迷神秘节目，身体产生诡异变异', rating: '7.5', douban: 'https://movie.douban.com/subject/1295276/', poster: 'https://image.tmdb.org/t/p/w500/qqqkiZSU9EBGZ1KiDmfn07S7qvv.jpg' },
    { year: 1984, title_cn: '毒魔复仇', title_en: 'The Toxic Avenger', country: '美国', desc: '清洁工掉进毒液桶变身超级英雄惩恶扬善', rating: '6.3', douban: 'https://movie.douban.com/subject/1299475/', poster: 'https://image.tmdb.org/t/p/w500/cCWojb6N9UcTzNVtS4bOM3vQ30x.jpg' },
    { year: 1985, title_cn: '活跳尸', title_en: 'Re-Animator', country: '美国', desc: '疯狂医学生发明复活药剂，死人暴走失控', rating: '7.2', douban: 'https://movie.douban.com/subject/1305793/', poster: 'https://image.tmdb.org/t/p/w500/1hY6AUl92cL9GdZx031UWFiGETt.jpg' },
    { year: 1986, title_cn: '变蝇人', title_en: 'The Fly', country: '美国/英国', desc: '科学家传送实验出错，基因与苍蝇融合逐渐异变', rating: '7.7', douban: 'https://movie.douban.com/subject/1293073/', poster: 'https://image.tmdb.org/t/p/w500/8gZWMhJHRvaXdXsNhERtqNHYpH3.jpg' },
    { year: 1987, title_cn: '猛鬼追魂', title_en: 'Hellraiser', country: '英国', desc: '魔方盒打开地狱之门，欲望与痛苦交织', rating: '7.3', douban: 'https://movie.douban.com/subject/2042941/', poster: 'https://image.tmdb.org/t/p/w500/3Z0oPHyLnk3Vx6ZMC1MiVwIrKhO.jpg' },
    { year: 1988, title_cn: '变形怪体', title_en: 'The Blob', country: '美国', desc: '外太空黏液怪物入侵小镇吞噬一切', rating: '6.8', douban: 'https://movie.douban.com/subject/1440617/', poster: 'https://image.tmdb.org/t/p/w500/zXXDmz5cPuSo9LveCNjZ1j16szC.jpg' },
    { year: 1989, title_cn: '上流社会', title_en: 'Society', country: '美国', desc: '少年发现上流社会家族的恐怖变形秘密', rating: '6.5', douban: 'https://movie.douban.com/subject/2265805/', poster: 'https://image.tmdb.org/t/p/w500/8Yg51sD6loLBYIlUcMDCO0bUGSh.jpg' },
    { year: 1990, title_cn: '科学怪妓', title_en: 'Frankenhooker', country: '美国', desc: '男子用妓女身体部件拼接复活未婚妻', rating: '5.8', douban: 'https://movie.douban.com/subject/1958342/', poster: 'https://image.tmdb.org/t/p/w500/s8Oubzkc2pPdOdj4D23ljZSKRbg.jpg' },
    { year: 1991, title_cn: '死而复生', title_en: 'The Resurrected', country: '美国', desc: '化学家痴迷复活实验，妻子揭开恐怖真相', rating: '6.2', douban: 'https://movie.douban.com/subject/2138008/', poster: 'https://image.tmdb.org/t/p/w500/nhQwgcIDD5XcKWLMLyrgqY4bFZd.jpg' },
    { year: 1992, title_cn: '群尸玩过界', title_en: 'Braindead', country: '新西兰', desc: '鼠猴咬人引发丧尸潮，电锯血浆大战', rating: '8.0', douban: 'https://movie.douban.com/subject/1300377/', poster: 'https://image.tmdb.org/t/p/w500/glUWJyqN9EUO2kb8rB0T1PUmiJU.jpg' },
    { year: 1993, title_cn: '融尸荡魂', title_en: 'Body Melt', country: '澳大利亚', desc: '药物实验导致居民身体恐怖融化变异', rating: '5.2', poster: 'https://image.tmdb.org/t/p/w500/3DhwXNsZ5X66aQi9VnJMPn1Xcsl.jpg' },
    { year: 1994, title_cn: '玛丽雪莱的科学怪人', title_en: "Mary Shelley's Frankenstein", country: '美国/日本/英国', desc: '科学家用尸体拼造新生命，怪物复仇悲剧', rating: '7.1', douban: 'https://movie.douban.com/subject/1293778/', poster: 'https://image.tmdb.org/t/p/w500/bOwCAQsZlEKrwhPi1ejY6BS8jpL.jpg' },
    { year: 1995, title_cn: '异种', title_en: 'Species', country: '美国', desc: '外星DNA培育的美女生物疯狂寻找配偶繁殖', rating: '6.1', douban: 'https://movie.douban.com/subject/1293442/', poster: 'https://image.tmdb.org/t/p/w500/cT5wdyo8kT7dycqjrolJ2sHWkFx.jpg' },
    { year: 1996, title_cn: '瘦到死', title_en: 'Thinner', country: '美国', desc: '肥胖律师被吉普赛人诅咒不断消瘦至死', rating: '6.4', douban: 'https://movie.douban.com/subject/1293390/', poster: 'https://image.tmdb.org/t/p/w500/nXqHqsQXA0jJpCaUsyre1Yw18oV.jpg' },
    { year: 1997, title_cn: '黑洞表面', title_en: 'Event Horizon', country: '英国/美国', desc: '失踪飞船重现，船员陷入地狱般的幻觉', rating: '7.0', douban: 'https://movie.douban.com/subject/1298041/', poster: 'https://image.tmdb.org/t/p/w500/qfluaDXv0cIdLwgQWzNB2piHL2q.jpg' },
    { year: 1998, title_cn: '我的老师不是人', title_en: 'The Faculty', country: '美国', desc: '高中生发现老师被外星寄生虫控制', rating: '6.7', douban: 'https://movie.douban.com/subject/1294732/', poster: 'https://image.tmdb.org/t/p/w500/5XetJwmAiDC0EtH23NIXaqFn3Wl.jpg' },
    { year: 1999, title_cn: '切肤之爱', title_en: 'Audition', country: '日本', desc: '中年丧偶男选妻遇上温柔变态少女', rating: '7.2', douban: 'https://movie.douban.com/subject/37219321/', poster: 'https://image.tmdb.org/t/p/w500/zwGaUMm0wAqi0wkO7LJDlwoA5LP.jpg' },
    { year: 2000, title_cn: '漩涡', title_en: 'Uzumaki', country: '日本', desc: '小镇被螺旋诅咒笼罩，居民身体扭曲变形', rating: '6.1', douban: 'https://movie.douban.com/subject/1308017/', poster: 'https://image.tmdb.org/t/p/w500/wtQIgqEQEIQnNqLVGTShUf7qLap.jpg' },
    { year: 2001, title_cn: '异魔禁区', title_en: 'Dagon', country: '西班牙', desc: '情侣漂流至诡异渔村，村民已变成鱼人', rating: '6.6', douban: 'https://movie.douban.com/subject/1695241/', poster: 'https://image.tmdb.org/t/p/w500/8S648eMKObi8ERFS7cSYDocxSaZ.jpg' },
    { year: 2002, title_cn: '切肤', title_en: 'In My Skin', country: '法国', desc: '女白领意外受伤后沉迷自我伤害无法自拔', rating: '6.5', douban: 'https://movie.douban.com/subject/1436885/', poster: 'https://image.tmdb.org/t/p/w500/v57vYRakOfsIvDaa4VcmysZgIV0.jpg' },
    { year: 2003, title_cn: '牛头', title_en: 'Gozu', country: '日本', desc: '黑帮小弟寻找消失的大哥，坠入超现实噩梦', rating: '7.0', douban: 'https://movie.douban.com/subject/1307866/', poster: 'https://image.tmdb.org/t/p/w500/9kWnamFFjyECih8JfJ6k0D42Kv8.jpg' },
    { year: 2004, title_cn: '机械师', title_en: 'The Machinist', country: '西班牙/美国', desc: '失眠一年的工人身体极度消瘦，精神崩溃', rating: '8.1', douban: 'https://movie.douban.com/subject/1309160/', poster: 'https://image.tmdb.org/t/p/w500/diAYqR4xdF9Hnj7qun6DEQhRrT2.jpg' },
    { year: 2005, title_cn: '恐怖蜡像馆', title_en: 'House of Wax', country: '美国/澳大利亚', desc: '年轻人误入小镇蜡像馆，蜡像竟是真人制成', rating: '6.5', douban: 'https://movie.douban.com/subject/1309184/', poster: 'https://image.tmdb.org/t/p/w500/aCLSgw1DaqkRvosYc3YUttBTtpT.jpg' },
    { year: 2006, title_cn: '撕裂人', title_en: 'Slither', country: '加拿大/美国', desc: '外星寄生虫入侵小镇，居民变异为恶心怪物', rating: '6.5', douban: 'https://movie.douban.com/subject/1465415/', poster: 'https://image.tmdb.org/t/p/w500/zNlJvCY3Pz7SE09Lf4G7uPs5XFZ.jpg' },
    { year: 2007, title_cn: '恐怖爆发', title_en: 'Exte: Hair Extensions', country: '日本', desc: '死尸头发疯长被制成假发，佩戴者离奇惨死', rating: '5.9', douban: 'https://movie.douban.com/subject/1939690/', poster: 'https://image.tmdb.org/t/p/w500/hhfjXQxMoZkknfO0TVQGZrGzIk5.jpg' },
    { year: 2008, title_cn: '恐怖废墟', title_en: 'The Ruins', country: '美国/德国/澳大利亚', desc: '年轻人探索玛雅遗迹被食人藤蔓寄生', rating: '5.8', douban: 'https://movie.douban.com/subject/2132486/', poster: 'https://image.tmdb.org/t/p/w500/6HpicbiT7xmlMjQXOSCeNoLZGpf.jpg' },
    { year: 2009, title_cn: '人体蜈蚣', title_en: 'The Human Centipede', country: '荷兰/英国', desc: '变态医生将三人缝合成首尾相连的人体蜈蚣', rating: '5.1', douban: 'https://movie.douban.com/subject/4058698/', poster: 'https://image.tmdb.org/t/p/w500/gMtjxIkEi0hnTV5lPHbgeZ4ZpUZ.jpg' },
    { year: 2010, title_cn: '战斗少女', title_en: 'Mutant Girls Squad', country: '日本', desc: '少女16岁觉醒变异能力，手臂化为利刃', rating: '5.4', douban: 'https://movie.douban.com/subject/4290700/', poster: 'https://image.tmdb.org/t/p/w500/zBlC14H3k1FpWgkwxp8K7mKVt52.jpg' },
    { year: 2011, title_cn: '吾栖之肤', title_en: 'The Skin I Live In', country: '西班牙', desc: '整形医生囚禁女子进行疯狂换肤实验', rating: '8.1', douban: 'https://movie.douban.com/subject/2997052/', poster: 'https://image.tmdb.org/t/p/w500/xa7uCwGYykrf8MMI8iF5dZvNlrG.jpg' },
    { year: 2012, title_cn: '病毒抗体', title_en: 'Antiviral', country: '加拿大/美国', desc: '未来世界贩卖明星病毒，员工私注感染濒死', rating: '5.8', douban: 'https://movie.douban.com/subject/6958992/', poster: 'https://image.tmdb.org/t/p/w500/rIn0ruFDU8psnCGkPgA9fbKJJUy.jpg' },
    { year: 2013, title_cn: '皮囊之下', title_en: 'Under the Skin', country: '英国/美国/瑞士', desc: '外星女子披人皮在苏格兰诱杀男性', rating: '6.5', douban: 'https://movie.douban.com/subject/3749974/', poster: 'https://image.tmdb.org/t/p/w500/55wmcXJIDYITr7JDijJTdvwSaAv.jpg' },
    { year: 2014, title_cn: '人形海象', title_en: 'Tusk', country: '美国', desc: '播客主持人被疯老头改造成人形海象', rating: '5.3', douban: 'https://movie.douban.com/subject/25770733/', poster: 'https://image.tmdb.org/t/p/w500/pA2SgITmH0lzet9Nn5cxeinRKMv.jpg' },
    { year: 2015, title_cn: '变蚊人', title_en: 'Bite', country: '加拿大', desc: '女子被虫咬后逐渐变异为产卵的昆虫怪物', rating: '4.3', douban: 'https://movie.douban.com/subject/26474493/', poster: 'https://image.tmdb.org/t/p/w500/a1FSymX7oo1tjrh4UPv6V03Co2v.jpg' },
    { year: 2016, title_cn: '虚空', title_en: 'The Void', country: '加拿大', desc: '医院被神秘教徒包围，内部现克苏鲁怪物', rating: '5.7', douban: 'https://movie.douban.com/subject/26427810/', poster: 'https://image.tmdb.org/t/p/w500/2WhZAPi3vomEQdzAPIYTvmvWaxI.jpg' },
    { year: 2017, title_cn: '生吃', title_en: 'Raw', country: '法国/比利时', desc: '素食少女进兽医学院后嗜血成瘾渴望生肉', rating: '7.1', douban: 'https://movie.douban.com/subject/26653833/', poster: 'https://image.tmdb.org/t/p/w500/pv5WNnLUo7mpT8k901Lo8UovrqI.jpg' },
    { year: 2018, title_cn: '阴风阵阵', title_en: 'Suspiria', country: '意大利/美国', desc: '舞蹈学院暗藏女巫集会，身体被扭曲操控', rating: '6.7', douban: 'https://movie.douban.com/subject/3095514/', poster: 'https://image.tmdb.org/t/p/w500/bRpKFPb8CWKRQxVo9NzOuPPlO3Q.jpg' },
    { year: 2019, title_cn: '海滨别墅', title_en: 'The Beach House', country: '美国', desc: '情侣海边度假遭神秘微生物感染，身体溃烂', rating: '4.7', douban: 'https://movie.douban.com/subject/34809725/', poster: 'https://image.tmdb.org/t/p/w500/gdGh7K00iaeD03EYqtXT70bivf4.jpg' },
    { year: 2020, title_cn: '占有者', title_en: 'Possessor', country: '加拿大/英国', desc: '女杀手通过脑植入控制他人身体执行暗杀', rating: '6.5', douban: 'https://movie.douban.com/subject/30220880/', poster: 'https://image.tmdb.org/t/p/w500/xC9GZeJZ3NagdkGg9nLQx0aPG6J.jpg' },
    { year: 2021, title_cn: '钛', title_en: 'Titane', country: '法国/比利时', desc: '脑中植入钛板的少女与汽车交合后怀孕变异', rating: '6.7', douban: 'https://movie.douban.com/subject/34820925/', poster: 'https://image.tmdb.org/t/p/w500/mBlpouG3gqB8WLdP65LCOXb3jFb.jpg' },
    { year: 2022, title_cn: '未来罪行', title_en: 'Crimes of the Future', country: '加拿大/法国/希腊/英国', desc: '未来人类随意改造身体，器官变异成为艺术', rating: '5.9', douban: 'https://movie.douban.com/subject/35448536/', poster: 'https://image.tmdb.org/t/p/w500/RAFYMC0NgK9In9aGY6k6wsIL8w.jpg' },
    { year: 2023, title_cn: '寄人皮下', title_en: 'Suitable Flesh', country: '美国', desc: '心理医生被患者夺舍，灵魂在不同身体间跳跃', rating: '5.5', douban: 'https://movie.douban.com/subject/36155146/', poster: 'https://image.tmdb.org/t/p/w500/tl3vIpRNKaWyMJiLxkpdT9Q2EWm.jpg' },
    { year: 2024, title_cn: '某种物质', title_en: 'The Substance', country: '法国/英国/美国', desc: '过气女星注射回春药物，代价是身体恐怖崩坏', rating: '7.5', douban: 'https://movie.douban.com/subject/35882838/', poster: 'https://image.tmdb.org/t/p/w500/lqoMzCcZYEFK729d6qzt349fB4o.jpg' },
    { year: 2025, title_cn: '丑陋的继姐', title_en: 'The Ugly Stepsister', country: '挪威/丹麦', desc: '灰姑娘黑暗改编，继姐为变美自残削骨', rating: '7.0', douban: 'https://movie.douban.com/subject/36471252/', poster: 'https://image.tmdb.org/t/p/w500/rayAREIKtSinuov10GvrZHyXfXH.jpg' },
  ],

  'cthulhu': [
    { year: 1963, title_cn: '闹鬼的宫殿', title_en: 'The Haunted Palace', country: '美国', desc: '男子继承古堡后被祖先亡灵附身复仇', rating: '6.3', douban: 'https://movie.douban.com/subject/1305468/', poster: 'https://image.tmdb.org/t/p/w500/nR1cuxMOPqHHapEzORa8RESKrWG.jpg' },
    { year: 1965, title_cn: '殉魔记', title_en: 'Die, Monster, Die!', country: '英国/美国', desc: '陨石坠落庄园，辐射导致生物恐怖变异', rating: '5.5', douban: 'https://movie.douban.com/subject/2131857/', poster: 'https://image.tmdb.org/t/p/w500/zv7z3cfHGg9TwDfInxsSRAzWc6z.jpg' },
    { year: 1968, title_cn: '深红祭坛的诅咒', title_en: 'Curse of the Crimson Altar', country: '英国', desc: '男子寻找失踪兄弟，卷入古老巫术仪式', rating: '5.6', poster: 'https://image.tmdb.org/t/p/w500/y45LdkyTdZvihACTjNNeUZZbbHD.jpg' },
    { year: 1970, title_cn: '敦威治恐怖事件', title_en: 'The Dunwich Horror', country: '美国', desc: '青年试图用魔法书召唤远古邪神降临人间', rating: '5.6', douban: 'https://movie.douban.com/subject/1780825/', poster: 'https://image.tmdb.org/t/p/w500/veoJRMZSk9RwTnDJmhhNj6WpJWx.jpg' },
    { year: 1981, title_cn: '鬼玩人', title_en: 'The Evil Dead', country: '美国', desc: '五人山间小屋度假，死灵之书唤醒远古恶魔', rating: '7.5', douban: 'https://movie.douban.com/subject/1300880/', poster: 'https://image.tmdb.org/t/p/w500/54C1qdaiSijIU5NeNb4WsPJdNkG.jpg' },
    { year: 1986, title_cn: '活魔人', title_en: 'From Beyond', country: '美国', desc: '科学家打开第六感官，引来异次元恐怖生物', rating: '6.6', douban: 'https://movie.douban.com/subject/1301878/', poster: 'https://image.tmdb.org/t/p/w500/zwmyxaKzIRLD4iUqZAQW940omdm.jpg' },
    { year: 1987, title_cn: '诅咒', title_en: 'The Curse', country: '美国', desc: '陨石坠落农场污染水源，全家人恐怖变异', rating: '5.8', poster: 'https://image.tmdb.org/t/p/w500/asAWax01LNj8w2bALu7vibUqEvb.jpg' },
    { year: 1988, title_cn: '天妖', title_en: 'The Unnamable', country: '美国', desc: '大学生闯入闹鬼老宅，遭遇不可名状之物', rating: '5.2', poster: 'https://image.tmdb.org/t/p/w500/A2hg2S2ATA7VjZe7GKkyaSRO5Ki.jpg' },
    { year: 1991, title_cn: '死而复生', title_en: 'The Resurrected', country: '美国', desc: '化学家痴迷复活实验，妻子揭开恐怖真相', rating: '6.2', douban: 'https://movie.douban.com/subject/2138008/', poster: 'https://image.tmdb.org/t/p/w500/nhQwgcIDD5XcKWLMLyrgqY4bFZd.jpg' },
    { year: 1993, title_cn: '死灵之书', title_en: 'Necronomicon', country: '美国', desc: '洛夫克拉夫特偷读死灵之书，三段恐怖故事', rating: '5.9', douban: 'https://movie.douban.com/subject/1461003/', poster: 'https://image.tmdb.org/t/p/w500/azUXnXC40LKxatud3sO8DvH1xR4.jpg' },
    { year: 1994, title_cn: '战栗黑洞', title_en: 'In the Mouth of Madness', country: '美国', desc: '调查员寻找失踪作家，现实与小说融为一体', rating: '7.6', douban: 'https://movie.douban.com/subject/1293765/', poster: 'https://image.tmdb.org/t/p/w500/msh4tEUzbnEqlHcFOUH4O0Zti8r.jpg' },
    { year: 1994, title_cn: '狂鬼吓人', title_en: 'Lurking Fear', country: '美国/罗马尼亚', desc: '小镇地下潜伏着嗜人怪物，幸存者绝望抵抗', rating: '4.8', poster: 'https://image.tmdb.org/t/p/w500/EiQ8WjBtW5VvHPHevrvnFCE0sB.jpg' },
    { year: 1995, title_cn: '衰落的城堡', title_en: 'Castle Freak', country: '美国/意大利', desc: '美国家庭继承意大利古堡，地牢藏着畸形怪物', rating: '5.6', douban: 'https://movie.douban.com/subject/1461840/', poster: 'https://image.tmdb.org/t/p/w500/HJEosQRIdBzAHEdZJCUF7e5FmF.jpg' },
    { year: 1997, title_cn: '黑洞表面', title_en: 'Event Horizon', country: '英国/美国', desc: '失踪飞船重现，船员陷入地狱般的幻觉', rating: '7.0', douban: 'https://movie.douban.com/subject/1298041/', poster: 'https://image.tmdb.org/t/p/w500/qfluaDXv0cIdLwgQWzNB2piHL2q.jpg' },
    { year: 2001, title_cn: '异魔禁区', title_en: 'Dagon', country: '西班牙', desc: '情侣漂流至诡异渔村，村民已变成鱼人', rating: '6.6', douban: 'https://movie.douban.com/subject/1695241/', poster: 'https://image.tmdb.org/t/p/w500/8S648eMKObi8ERFS7cSYDocxSaZ.jpg' },
    { year: 2005, title_cn: '克苏鲁的召唤', title_en: 'The Call of Cthulhu', country: '美国', desc: '默片风格改编洛夫克拉夫特同名经典小说', rating: '7.3', douban: 'https://movie.douban.com/subject/1866805/', poster: 'https://image.tmdb.org/t/p/w500/dCrOkzrWs8ux31oVCc1R8tt6zTC.jpg' },
    { year: 2007, title_cn: '迷雾', title_en: 'The Mist', country: '美国', desc: '浓雾笼罩小镇，雾中藏着来自异次元的怪物', rating: '7.9', douban: 'https://movie.douban.com/subject/1945330/', poster: 'https://image.tmdb.org/t/p/w500/1CvJ6diBACKPVGOpcWuY4XPQdqX.jpg' },
    { year: 2010, title_cn: '瓦德玛尔阴宅2', title_en: 'The Valdemar Legacy II', country: '西班牙', desc: '阴宅深处隐藏通往异界的门，克苏鲁降临', rating: '5.3', poster: 'https://image.tmdb.org/t/p/w500/tYTe2HRLBWgHpgNfEoRASxee60C.jpg' },
    { year: 2011, title_cn: '黑山羊', title_en: 'The Black Goat', country: '日本', desc: '少女在封闭村庄遭遇远古邪神崇拜仪式', rating: '5.0' },
    { year: 2014, title_cn: '爱在初春惊变时', title_en: 'Spring', country: '美国', desc: '青年在意大利邂逅神秘女子，她有远古秘密', rating: '6.3', douban: 'https://movie.douban.com/subject/25900945/', poster: 'https://image.tmdb.org/t/p/w500/Rf2tzfQPHooSlVbxI2EScuJcN6.jpg' },
    { year: 2015, title_cn: '魔女屋中之梦', title_en: 'Dreams in the Witch House', country: '美国', desc: '改编洛夫克拉夫特，学生租住女巫旧居噩梦连连', rating: '5.7', poster: 'https://image.tmdb.org/t/p/w500/8ymDDhDNGHXdU7bnXbMaFvVn5gG.jpg' },
    { year: 2016, title_cn: '虚空', title_en: 'The Void', country: '加拿大', desc: '医院被神秘教徒包围，内部现克苏鲁怪物', rating: '5.7', douban: 'https://movie.douban.com/subject/26427810/', poster: 'https://image.tmdb.org/t/p/w500/2WhZAPi3vomEQdzAPIYTvmvWaxI.jpg' },
    { year: 2018, title_cn: '湮灭', title_en: 'Annihilation', country: '美国/英国', desc: '女科学家深入神秘区域，基因被未知力量改写', rating: '7.2', douban: 'https://movie.douban.com/subject/21348914/', poster: 'https://image.tmdb.org/t/p/w500/4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg' },
    { year: 2019, title_cn: '星之彩', title_en: 'Color Out of Space', country: '美国/葡萄牙/马来西亚', desc: '陨石坠落农场释放外星颜色，全家疯狂变异', rating: '6.0', douban: 'https://movie.douban.com/subject/30147027/', poster: 'https://image.tmdb.org/t/p/w500/k7rD7LzlsPS4jmE6Siah0QO4tAc.jpg' },
    { year: 2019, title_cn: '灯塔', title_en: 'The Lighthouse', country: '美国/加拿大', desc: '两个守塔人困在孤岛，在疯狂中坠入深渊', rating: '7.4', douban: 'https://movie.douban.com/subject/30143336/', poster: 'https://image.tmdb.org/t/p/w500/f1tIYarTbkBdIT1aW0gzelDwknv.jpg' },
    { year: 2020, title_cn: '深潜者', title_en: 'Underwater', country: '美国', desc: '深海钻井队遭遇远古巨型生物攻击', rating: '6.2', douban: 'https://movie.douban.com/subject/26348579/', poster: 'https://image.tmdb.org/t/p/w500/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg' },
    { year: 2020, title_cn: '躯壳', title_en: 'The Husk', country: '美国', desc: '人体被外星寄生体改造成新形态', rating: '4.5', poster: 'https://image.tmdb.org/t/p/w500/sUZsFqjqzBS0rhXWMZnvcF4qjJf.jpg' },
    { year: 2020, title_cn: '深海异兽', title_en: 'Sea Fever', country: '爱尔兰/瑞典/比利时', desc: '渔船被深海未知生物寄生，船员逐个感染', rating: '5.7', douban: 'https://movie.douban.com/subject/30394117/', poster: 'https://image.tmdb.org/t/p/w500/h4cPVVNPZUHVeoF6dH2grBvSEKs.jpg' },
    { year: 2023, title_cn: '寄人皮下', title_en: 'Suitable Flesh', country: '美国', desc: '心理医生被患者夺舍，灵魂在不同身体间跳跃', rating: '5.5', douban: 'https://movie.douban.com/subject/36155146/', poster: 'https://image.tmdb.org/t/p/w500/tl3vIpRNKaWyMJiLxkpdT9Q2EWm.jpg' },
  ],

  'rob-zombie': [
    { year: 2003, title_cn: '千尸屋', title_en: 'House of 1000 Corpses', country: '美国', desc: '四个年轻人误闯变态家族的恐怖屋', rating: '6.3', douban: 'https://movie.douban.com/subject/1306288/', poster: 'https://image.tmdb.org/t/p/w500/29c2qgXmSREosLBevOILEuMWzQC.jpg' },
    { year: 2005, title_cn: '千尸屋2', title_en: "The Devil's Rejects", country: '美国', desc: '变态家族被警方追捕，一路血腥逃亡', rating: '6.8', douban: 'https://movie.douban.com/subject/1418736/', poster: 'https://image.tmdb.org/t/p/w500/gK6fR3u7rMjjWwbsAqD8ShH4VoS.jpg' },
    { year: 2007, title_cn: '万圣节', title_en: 'Halloween', country: '美国', desc: '迈克尔·迈尔斯的起源故事，重启经典', rating: '6.2', douban: 'https://movie.douban.com/subject/1793929/', poster: 'https://image.tmdb.org/t/p/w500/cD8JrfSEI4j7WVnKM1GdiYzMoUh.jpg' },
    { year: 2009, title_cn: '万圣节2', title_en: 'Halloween II', country: '美国', desc: '迈克尔·迈尔斯再次归来，更加残暴', rating: '5.5', poster: 'https://image.tmdb.org/t/p/w500/vSHPM4LQDpWdQrD5KZWK6wNqSOD.jpg' },
    { year: 2012, title_cn: '赛勒姆领主', title_en: 'The Lords of Salem', country: '美国/加拿大/英国', desc: '电台DJ收到神秘唱片，唤醒赛勒姆女巫诅咒', rating: '5.3', douban: 'https://movie.douban.com/subject/4820752/', poster: 'https://image.tmdb.org/t/p/w500/nqZ6CGGZpQWt139YioekSYHvvkU.jpg' },
    { year: 2016, title_cn: '31', title_en: '31', country: '美国', desc: '万圣节前夜五人被迫参加12小时杀人游戏', rating: '5.0', douban: 'https://movie.douban.com/subject/25870048/', poster: 'https://image.tmdb.org/t/p/w500/jHkIIkP4O0vUkSACcizOPZQIiF7.jpg' },
    { year: 2019, title_cn: '千尸屋3', title_en: '3 from Hell', country: '美国', desc: '变态家族越狱后继续疯狂杀戮之旅', rating: '5.4', douban: 'https://movie.douban.com/subject/27109131/', poster: 'https://image.tmdb.org/t/p/w500/iaURDnsqwTpFdg7RuizUp0nI2I4.jpg' },
    { year: 2022, title_cn: '蒙斯特一家', title_en: 'The Munsters', country: '美国', desc: '经典怪物家庭喜剧重启，Rob Zombie执导', rating: '4.2', douban: 'https://movie.douban.com/subject/35215390/', poster: 'https://image.tmdb.org/t/p/w500/zrITsKZPVjMMZtsIDn1hAB7gyWE.jpg' },
  ],

  'tim-burton': [
    { year: 1985, title_cn: '荒唐小混蛋奇遇记', title_en: "Pee-wee's Big Adventure", country: '美国', desc: '怪咖男孩横跨美国寻找被偷的自行车', rating: '6.6', poster: 'https://image.tmdb.org/t/p/w500/4Oe5DGK9mlMQ0JkuWlfOMRL0qCA.jpg' },
    { year: 1988, title_cn: '甲壳虫汁', title_en: 'Beetlejuice', country: '美国', desc: '新死夫妇请来恶灵驱赶占据老屋的活人', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg' },
    { year: 1989, title_cn: '蝙蝠侠', title_en: 'Batman', country: '美国/英国', desc: '黑暗骑士对抗疯狂小丑，哥特风格开山之作', rating: '7.4', douban: 'https://movie.douban.com/subject/1292217/', poster: 'https://image.tmdb.org/t/p/w500/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg' },
    { year: 1990, title_cn: '剪刀手爱德华', title_en: 'Edward Scissorhands', country: '美国', desc: '双手是剪刀的人造人闯入郊区小镇的温情悲剧', rating: '8.7', douban: 'https://movie.douban.com/subject/1292370/', poster: 'https://image.tmdb.org/t/p/w500/e0FqKFvGPdQNWG8tF9cZBtev9Em.jpg' },
    { year: 1992, title_cn: '蝙蝠侠归来', title_en: 'Batman Returns', country: '美国/英国', desc: '蝙蝠侠对抗企鹅人和猫女，更加黑暗扭曲', rating: '7.2', douban: 'https://movie.douban.com/subject/1292218/', poster: 'https://image.tmdb.org/t/p/w500/uEIvgvxzK08922iU61OvO3ORs0s.jpg' },
    { year: 1994, title_cn: '艾德·伍德', title_en: 'Ed Wood', country: '美国', desc: '史上最烂导演的传奇人生，致敬B级片精神', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/n8SrO3WbyuY2b6KazogqbQF348C.jpg' },
    { year: 1996, title_cn: '火星人玩转地球', title_en: 'Mars Attacks!', country: '美国', desc: '火星人入侵地球，黑色幽默讽刺全明星阵容', rating: '7.0', douban: 'https://movie.douban.com/subject/1293182/', poster: 'https://image.tmdb.org/t/p/w500/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg' },
    { year: 1999, title_cn: '断头谷', title_en: 'Sleepy Hollow', country: '美国/德国', desc: '警探调查无头骑士连环斩首案，哥特恐怖经典', rating: '7.6', douban: 'https://movie.douban.com/subject/1292360/', poster: 'https://image.tmdb.org/t/p/w500/2RHj62XneYMCRPAyQrEIrKVij12.jpg' },
    { year: 2001, title_cn: '决战猩球', title_en: 'Planet of the Apes', country: '美国', desc: '宇航员坠落猿族统治的星球，人类沦为奴隶', rating: '6.6', douban: 'https://movie.douban.com/subject/1293025/', poster: 'https://image.tmdb.org/t/p/w500/2r9iKnlSYEk4daQadsXfcjHfIjQ.jpg' },
    { year: 2003, title_cn: '大鱼', title_en: 'Big Fish', country: '美国', desc: '儿子试图分辨父亲传奇故事中的真实与虚构', rating: '8.8', douban: 'https://movie.douban.com/subject/1291545/', poster: 'https://image.tmdb.org/t/p/w500/8gLc3LKww5j2wxhWcrzhdKGvcGU.jpg' },
    { year: 2005, title_cn: '查理和巧克力工厂', title_en: 'Charlie and the Chocolate Factory', country: '美国/英国', desc: '穷男孩获金券参观古怪巧克力大王的奇幻工厂', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/iKP6wg3c6COUe8gYutoGG7qcPnO.jpg' },
    { year: 2005, title_cn: '僵尸新娘', title_en: 'Corpse Bride', country: '美国/英国', desc: '男子误将戒指戴给地下僵尸新娘，阴阳两难', rating: '8.2', douban: 'https://movie.douban.com/subject/1308782/', poster: 'https://image.tmdb.org/t/p/w500/isb2Qow76GpqYmsSyfdMfsYAjts.jpg' },
    { year: 2007, title_cn: '理发师陶德', title_en: 'Sweeney Todd', country: '美国/英国', desc: '复仇理发师用剃刀割喉，搭档做成肉馅饼', rating: '7.6', poster: 'https://image.tmdb.org/t/p/w500/gAW4J1bkRjZKmFsJsIiOBASeoAp.jpg' },
    { year: 2010, title_cn: '爱丽丝梦游仙境', title_en: 'Alice in Wonderland', country: '美国', desc: '爱丽丝重返仙境对抗红皇后，视觉奇幻盛宴', rating: '6.6', poster: 'https://image.tmdb.org/t/p/w500/o0kre9wRCZz3jjSjaru7QU0UtFz.jpg' },
    { year: 2012, title_cn: '黑暗阴影', title_en: 'Dark Shadows', country: '美国', desc: '200年前被诅咒的吸血鬼在70年代苏醒', rating: '6.2', poster: 'https://image.tmdb.org/t/p/w500/eRtnI7qTJIiPUmlY3J8TTM3jlT7.jpg' },
    { year: 2012, title_cn: '科学怪狗', title_en: 'Frankenweenie', country: '美国', desc: '男孩用科学实验复活爱犬，引发怪物连锁反应', rating: '7.3', poster: 'https://image.tmdb.org/t/p/w500/yGjVbLVdZRBlZTTQVBsj2KUjL1s.jpg' },
    { year: 2014, title_cn: '大眼睛', title_en: 'Big Eyes', country: '美国', desc: '画家丈夫冒名顶替妻子画作，真相终被揭露', rating: '7.1', poster: 'https://image.tmdb.org/t/p/w500/203HAjJcLMl7xThcTqZx4zmEGcV.jpg' },
    { year: 2016, title_cn: '佩小姐的奇幻城堡', title_en: "Miss Peregrine's Home for Peculiar Children", country: '美国/英国/比利时', desc: '男孩发现祖父秘密，进入异能儿童的时间循环', rating: '6.7', poster: 'https://image.tmdb.org/t/p/w500/CIlbMFOfYDj0MP23hsIYhFGrL6.jpg' },
    { year: 2019, title_cn: '小飞象', title_en: 'Dumbo', country: '美国', desc: '大耳小象被马戏团利用，孩子们帮它获得自由', rating: '6.5', poster: 'https://image.tmdb.org/t/p/w500/kTF2omZq1izOeplnnSACxhs4NLF.jpg' },
    { year: 2024, title_cn: '甲壳虫汁2', title_en: 'Beetlejuice Beetlejuice', country: '美国', desc: '时隔36年恶灵再度归来，三代人的哥特喜剧', rating: '6.4', poster: 'https://image.tmdb.org/t/p/w500/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg' },
  ],

  'john-carpenter': [
    { year: 1974, title_cn: '黑星球', title_en: 'Dark Star', country: '美国', desc: '四人太空船执行炸星任务，荒诞黑色喜剧', rating: '6.6', douban: 'https://movie.douban.com/subject/1296456/', poster: 'https://image.tmdb.org/t/p/w500/aiqLBiH0IWrog2Q78dZTT8Ad9Sp.jpg' },
    { year: 1976, title_cn: '血溅十三号警署', title_en: 'Assault on Precinct 13', country: '美国', desc: '废弃警局被帮派围攻，警匪联手殊死搏斗', rating: '7.3', douban: 'https://movie.douban.com/subject/1300073/', poster: 'https://image.tmdb.org/t/p/w500/RtGDEmXbSxE8NThCCY1SXFXLLw.jpg' },
    { year: 1978, title_cn: '月光光心慌慌', title_en: 'Halloween', country: '美国', desc: '杀人狂迈克尔万圣夜越狱回乡，砍杀式恐怖鼻祖', rating: '7.7', poster: 'https://image.tmdb.org/t/p/w500/cD8JrfSEI4j7WVnKM1GdiYzMoUh.jpg' },
    { year: 1980, title_cn: '雾', title_en: 'The Fog', country: '美国', desc: '浓雾中亡灵水手回归小镇复仇', rating: '6.7', poster: 'https://image.tmdb.org/t/p/w500/12EeSboRofP3CI4SPmMFNNXCbtY.jpg' },
    { year: 1981, title_cn: '纽约大逃亡', title_en: 'Escape from New York', country: '美国/英国', desc: '未来纽约沦为监狱，独眼佣兵深入救总统', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/vH9llaphjAssRGi0k7e75tD40Ce.jpg' },
    { year: 1982, title_cn: '怪形', title_en: 'The Thing', country: '美国', desc: '南极科考队遭遇能模仿任何生物的外星怪物', rating: '8.2', douban: 'https://movie.douban.com/subject/1296794/', poster: 'https://image.tmdb.org/t/p/w500/tzGY49kseSE9QAKk47uuDGwnSCu.jpg' },
    { year: 1983, title_cn: '克里斯汀魅力', title_en: 'Christine', country: '美国', desc: '被附身的1958年普利茅斯汽车疯狂杀人', rating: '6.7', poster: 'https://image.tmdb.org/t/p/w500/mMtUJke2TtIoT6JB9hkvERmsSu8.jpg' },
    { year: 1984, title_cn: '外星恋', title_en: 'Starman', country: '美国', desc: '外星人化身已故丈夫形象，与妻子踏上旅途', rating: '7.0', poster: 'https://image.tmdb.org/t/p/w500/4fKXWIiaLTQDvOS5Ok4XfD5qKJb.jpg' },
    { year: 1986, title_cn: '妖魔大闹唐人街', title_en: 'Big Trouble in Little China', country: '美国', desc: '卡车司机闯入旧金山地下，对抗千年妖魔', rating: '7.1', poster: 'https://image.tmdb.org/t/p/w500/gI2Qs1yTTj3NcESJyttCkbmJ4k9.jpg' },
    { year: 1987, title_cn: '天魔回魂', title_en: 'Prince of Darkness', country: '美国', desc: '教堂地下室发现撒旦之子，科学与信仰碰撞', rating: '6.7', poster: 'https://image.tmdb.org/t/p/w500/jjcAOhtGuX4p8XvlVn1WXUT1jWi.jpg' },
    { year: 1988, title_cn: '极度空间', title_en: 'They Live', country: '美国', desc: '流浪汉戴上墨镜看到外星人伪装统治人类', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/ngnybFTuopfbfmmEeX9jjBQQmF6.jpg' },
    { year: 1992, title_cn: '透明人的故事', title_en: 'Memoirs of an Invisible Man', country: '美国', desc: '意外隐身的男人被CIA追捕，逃亡中寻找解药', rating: '6.3', poster: 'https://image.tmdb.org/t/p/w500/zbplzn4WrBkKDmmWlQkWdsacmNa.jpg' },
    { year: 1994, title_cn: '战栗黑洞', title_en: 'In the Mouth of Madness', country: '美国', desc: '调查员寻找失踪作家，现实与小说融为一体', rating: '7.6', douban: 'https://movie.douban.com/subject/1293765/', poster: 'https://image.tmdb.org/t/p/w500/msh4tEUzbnEqlHcFOUH4O0Zti8r.jpg' },
    { year: 1995, title_cn: '魔童村', title_en: 'Village of the Damned', country: '美国', desc: '小镇女性集体怀孕，生下拥有超能力的恐怖儿童', rating: '5.8', poster: 'https://image.tmdb.org/t/p/w500/pXXNmSVqkvSMoMitsdjK0V8Dkna.jpg' },
    { year: 1996, title_cn: '洛杉矶大逃亡', title_en: 'Escape from L.A.', country: '美国', desc: '独眼蛇再入沦陷的洛杉矶执行任务', rating: '5.8', poster: 'https://image.tmdb.org/t/p/w500/3L9lL2eUsmLNNfENPwNOc82Hzpw.jpg' },
    { year: 1998, title_cn: '吸血鬼', title_en: 'Vampires', country: '美国', desc: '猎人团队追杀远古吸血鬼大师，阻止黑暗仪式', rating: '6.1', poster: 'https://image.tmdb.org/t/p/w500/4JhaFBPwyC5IM1rKaRR07Gzutse.jpg' },
    { year: 2001, title_cn: '火星幽灵', title_en: 'Ghosts of Mars', country: '美国', desc: '火星殖民地被远古幽灵附身，变成嗜杀狂战士', rating: '5.5', poster: 'https://image.tmdb.org/t/p/w500/i2zztssCIbahGES1fdfWFmDXian.jpg' },
    { year: 2010, title_cn: '鬼病院', title_en: 'The Ward', country: '美国', desc: '精神病院女患者逐个神秘消失，真相令人崩溃', rating: '5.8', douban: 'https://movie.douban.com/subject/4006150/', poster: 'https://image.tmdb.org/t/p/w500/k53uFP8lLCinMQGP4bY6kuwKLp8.jpg' },
  ],

  'stephen-king': [
    { year: 1976, title_cn: '魔女嘉莉', title_en: 'Carrie', country: '美国', desc: '被欺凌的少女在舞会上爆发念力血洗全场', rating: '7.6', douban: 'https://movie.douban.com/subject/1293493/', poster: 'https://image.tmdb.org/t/p/w500/8tT1rqlsTguyfUBMrbHR9cv1rxM.jpg' },
    { year: 1980, title_cn: '闪灵', title_en: 'The Shining', country: '美国/英国', desc: '作家带家人看管雪山酒店，逐渐被邪灵吞噬', rating: '8.2', douban: 'https://movie.douban.com/subject/1292225/', poster: 'https://image.tmdb.org/t/p/w500/zXKCwVNVsvYeg2XapKXszm5x9tZ.jpg' },
    { year: 1983, title_cn: '克里斯汀魅力', title_en: 'Christine', country: '美国', desc: '被附身的1958年汽车疯狂杀人', rating: '6.7', poster: 'https://image.tmdb.org/t/p/w500/mMtUJke2TtIoT6JB9hkvERmsSu8.jpg' },
    { year: 1984, title_cn: '玉米地的小孩', title_en: 'Children of the Corn', country: '美国', desc: '小镇儿童集体杀死成年人，在玉米地祭祀邪神', rating: '5.8', poster: 'https://image.tmdb.org/t/p/w500/jJTrFHu3rjAgP1lryKGEsC9hqyM.jpg' },
    { year: 1986, title_cn: '伴我同行', title_en: 'Stand by Me', country: '美国', desc: '四个少年踏上寻找尸体的冒险之旅', rating: '8.9', poster: 'https://image.tmdb.org/t/p/w500/vz0w9BSehcqjDcJOjRaCk7fgJe7.jpg' },
    { year: 1989, title_cn: '宠物坟场', title_en: 'Pet Sematary', country: '美国', desc: '印第安墓地能复活死者，但回来的不再是从前', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/a1gIACZb04bL8EvLqMpofW2Eqeo.jpg' },
    { year: 1990, title_cn: '危情十日', title_en: 'Misery', country: '美国', desc: '作家被头号粉丝囚禁，强迫他写出满意的结局', rating: '8.2', poster: 'https://image.tmdb.org/t/p/w500/klPO5oh1LOxiPpdDXZo1ADgpKcw.jpg' },
    { year: 1990, title_cn: '小丑回魂', title_en: 'It', country: '美国', desc: '小镇下水道藏着变形恶魔小丑，27年一轮回', rating: '7.1', poster: 'https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg' },
    { year: 1994, title_cn: '肖申克的救赎', title_en: 'The Shawshank Redemption', country: '美国', desc: '银行家含冤入狱，用智慧和耐心挖出自由之路', rating: '9.7', douban: 'https://movie.douban.com/subject/1292052/', poster: 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg' },
    { year: 1995, title_cn: '热泪伤痕', title_en: 'Dolores Claiborne', country: '美国', desc: '女佣被控谋杀雇主，揭开尘封多年的家庭暗伤', rating: '7.9', poster: 'https://image.tmdb.org/t/p/w500/iQuwx3UAyXbE9tzdM3jLqtbogc4.jpg' },
    { year: 1999, title_cn: '绿里奇迹', title_en: 'The Green Mile', country: '美国', desc: '死囚拥有神奇治愈力，善良灵魂面对残酷命运', rating: '8.8', poster: 'https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg' },
    { year: 2007, title_cn: '1408', title_en: '1408', country: '美国', desc: '作家入住闹鬼酒店房间，陷入层层噩梦', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/yE9MCW7ZNxSw5SC1TMqm51pMBIV.jpg' },
    { year: 2007, title_cn: '迷雾', title_en: 'The Mist', country: '美国', desc: '浓雾笼罩小镇，雾中藏着来自异次元的怪物', rating: '7.9', poster: 'https://image.tmdb.org/t/p/w500/1CvJ6diBACKPVGOpcWuY4XPQdqX.jpg' },
    { year: 2017, title_cn: '小丑回魂', title_en: 'It', country: '美国/加拿大', desc: '七个少年对抗下水道变形恶魔小丑', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg' },
    { year: 2019, title_cn: '睡梦医生', title_en: 'Doctor Sleep', country: '美国/英国', desc: '闪灵续集，丹尼长大后对抗吸取儿童灵能的邪教', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/p69QzIBbN06aTYqRRiCOY1emNBh.jpg' },
    { year: 2019, title_cn: '宠物坟场', title_en: 'Pet Sematary', country: '美国', desc: '重启版，死去的女儿从墓地归来不再是从前', rating: '5.5', poster: 'https://image.tmdb.org/t/p/w500/a1gIACZb04bL8EvLqMpofW2Eqeo.jpg' },
  ],

  'del-toro': [
    { year: 1993, title_cn: '魔鬼银爪', title_en: 'Cronos', country: '墨西哥', desc: '古董商发现永生装置，代价是变成嗜血怪物', rating: '7.1', poster: 'https://image.tmdb.org/t/p/w500/bRX8au50CnhC8hXr8AbsCNdb96G.jpg' },
    { year: 1997, title_cn: '变种DNA', title_en: 'Mimic', country: '美国', desc: '基因改造昆虫进化成人形，潜伏在地铁隧道', rating: '6.7', poster: 'https://image.tmdb.org/t/p/w500/ieRRo78f8JzEKxfiCKqJyFg6l8o.jpg' },
    { year: 2001, title_cn: '鬼童院', title_en: "The Devil's Backbone", country: '西班牙/墨西哥', desc: '内战时期孤儿院闹鬼，男孩揭开炸弹与亡灵秘密', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/gK6fR3u7rMjjWwbsAqD8ShH4VoS.jpg' },
    { year: 2002, title_cn: '刀锋战士2', title_en: 'Blade II', country: '美国/德国', desc: '吸血鬼猎人联手吸血鬼对抗变异嗜血新种族', rating: '7.0', poster: 'https://image.tmdb.org/t/p/w500/yDHwo3eWcMiy5LnnEnlGV9iLu9k.jpg' },
    { year: 2004, title_cn: '地狱男爵', title_en: 'Hellboy', country: '美国', desc: '二战召唤的恶魔婴儿长大后为人类对抗超自然', rating: '7.0', poster: 'https://image.tmdb.org/t/p/w500/lbaTEneOofwvAyg77R8HbFML2zT.jpg' },
    { year: 2006, title_cn: '潘神的迷宫', title_en: "Pan's Labyrinth", country: '西班牙/墨西哥/美国', desc: '内战阴影下少女进入奇幻地下王国完成三个任务', rating: '8.0', poster: 'https://image.tmdb.org/t/p/w500/w8i0mZR7MEL7c3bXSsuYg7VJsew.jpg' },
    { year: 2008, title_cn: '地狱男爵2：黄金军团', title_en: 'Hellboy II: The Golden Army', country: '美国/德国', desc: '精灵王子率黄金军团进攻人类世界', rating: '7.1', poster: 'https://image.tmdb.org/t/p/w500/zO0Wdrxnhx3KoJEvychSmnY3urC.jpg' },
    { year: 2013, title_cn: '环太平洋', title_en: 'Pacific Rim', country: '美国', desc: '巨型机甲战士对抗深海裂缝涌出的怪兽军团', rating: '7.7', poster: 'https://image.tmdb.org/t/p/w500/8wo4eN8dWKaKlxhSvBz19uvj8gA.jpg' },
    { year: 2015, title_cn: '猩红山峰', title_en: 'Crimson Peak', country: '美国/加拿大', desc: '新娘嫁入阴森古宅，红色黏土下埋藏血腥秘密', rating: '6.4', poster: 'https://image.tmdb.org/t/p/w500/f9TOb5anVwZeSbYjU1qNxPk3KUk.jpg' },
    { year: 2017, title_cn: '水形物语', title_en: 'The Shape of Water', country: '美国', desc: '哑女清洁工与被囚的两栖人坠入爱河', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg' },
    { year: 2021, title_cn: '玉面情魔', title_en: 'Nightmare Alley', country: '美国/墨西哥/加拿大', desc: '野心家在嘉年华学会读心术，一步步走向毁灭', rating: '6.9', poster: 'https://image.tmdb.org/t/p/w500/vfn1feL0V9HNSXuLLpaxAW8O6LO.jpg' },
    { year: 2022, title_cn: '匹诺曹', title_en: "Guillermo del Toro's Pinocchio", country: '美国/墨西哥', desc: '定格动画黑暗版匹诺曹，法西斯时代的生死寓言', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/gldeyCtKcaqnK1v4Vu9vqayhzUQ.jpg' },
  ],

  'cult-top10': [
    { year: 1975, title_cn: '索多玛120天', title_en: 'Salò, or the 120 Days of Sodom', country: '意大利/法国', desc: '权力如何异化人，极端到让人不适的不只是画面', rating: '7.6', douban: 'https://movie.douban.com/subject/1296Mo/', poster: 'https://image.tmdb.org/t/p/w500/xnaDdiRfZlJaTf6JRc4in40eaeI.jpg' },
    { year: 1981, title_cn: '着魔', title_en: 'Possession', country: '法国/西德', desc: '地铁通道封神表演，婚姻崩坏与冷战压力的极致表达', rating: '7.9', douban: 'https://movie.douban.com/subject/1293660/', poster: 'https://image.tmdb.org/t/p/w500/lUFZsUuJ0YyhBXH8D2BFUd6wODm.jpg' },
    { year: 1983, title_cn: '焦虑', title_en: 'Angst', country: '奥地利', desc: '跟拍杀人、无心理铺垫，纯粹的暴力与邪恶', rating: '7.3', douban: 'https://movie.douban.com/subject/1437109/', poster: 'https://image.tmdb.org/t/p/w500/nSYdWrPPwvcs5t5hG67XqDbwncG.jpg' },
    { year: 1989, title_cn: '铁男', title_en: 'Tetsuo: The Iron Man', country: '日本', desc: '工业噪音美学的cult入门作，导演风格极致体现', rating: '7.3', douban: 'https://movie.douban.com/subject/1295773/', poster: 'https://image.tmdb.org/t/p/w500/hufXkmILGy34VXEdQC69etY8Rt4.jpg' },
    { year: 1992, title_cn: '群尸玩过界', title_en: 'Braindead', country: '新西兰', desc: '彼得·杰克逊经典cult代表作，血浆恶趣味但极有娱乐性', rating: '8.0', douban: 'https://movie.douban.com/subject/1300377/', poster: 'https://image.tmdb.org/t/p/w500/glUWJyqN9EUO2kb8rB0T1PUmiJU.jpg' },
    { year: 1997, title_cn: '迷失高速', title_en: 'Lost Highway', country: '美国/法国', desc: '大卫·林奇的身份裂变与诡异梦境感', rating: '7.8', douban: 'https://movie.douban.com/subject/1294117/', poster: 'https://image.tmdb.org/t/p/w500/fdTtij6H0sX9AzIjUeynh5zbfm7.jpg' },
    { year: 2001, title_cn: '杀手阿一', title_en: 'Ichi the Killer', country: '日本', desc: '暴力狂欢、极致重口，喜欢cult片就不能没看过', rating: '7.3', douban: 'https://movie.douban.com/subject/1308743/', poster: 'https://image.tmdb.org/t/p/w500/k8j4YLZlda98dqp9ErymKzjYowG.jpg' },
    { year: 2003, title_cn: '极道恐怖大剧场：牛头', title_en: 'Gozu', country: '日本', desc: '三池崇史发疯式作品，神经质荒诞带实验感', rating: '7.0', douban: 'https://movie.douban.com/subject/1307866/', poster: 'https://image.tmdb.org/t/p/w500/9kWnamFFjyECih8JfJ6k0D42Kv8.jpg' },
    { year: 2008, title_cn: '爱的曝光', title_en: 'Love Exposure', country: '日本', desc: '邪教、暴力、爱，叙事反复与扭曲的cult代表作', rating: '8.5', douban: 'https://movie.douban.com/subject/3172erta/', poster: 'https://image.tmdb.org/t/p/w500/3QSGUdzG374H7pOxIdKNBpeLEUk.jpg' },
    { year: 2010, title_cn: '冰冷热带鱼', title_en: 'Cold Fish', country: '日本', desc: '园子温代表作，日本家庭压抑下的变态控制与异化', rating: '7.6', douban: 'https://movie.douban.com/subject/4888529/', poster: 'https://image.tmdb.org/t/p/w500/669GmEZsyMlPliURX5myHTStslv.jpg' },
  ],

  'horror-top10': [
    { year: 2002, title_cn: '咒怨', title_en: 'Ju-On: The Grudge', country: '日本', desc: '日式恐怖经典，进入那栋房子的人都难逃诅咒', rating: '7.4', douban: 'https://movie.douban.com/subject/1302579/', poster: 'https://image.tmdb.org/t/p/w500/6q1hlBC6rudc3mHwXsbMBR2xAT6.jpg' },
    { year: 2004, title_cn: '鬼影', title_en: 'Shutter', country: '泰国', desc: '照片中的灵异身影，泰国心理惊悚代表作', rating: '7.5', douban: 'https://movie.douban.com/subject/1416277/', poster: 'https://image.tmdb.org/t/p/w500/zUyaVtyugDaDHtOC6kCMJhbZsWu.jpg' },
    { year: 2004, title_cn: '感染', title_en: 'Infection', country: '日本', desc: '医院深夜的诡异感染事件，日式心理恐怖', rating: '6.4', douban: 'https://movie.douban.com/subject/1416459/', poster: 'https://image.tmdb.org/t/p/w500/zCMSiJQ0iigWKaizcHN6Qv0tGqz.jpg' },
    { year: 2007, title_cn: '死寂', title_en: 'Dead Silence', country: '美国', desc: '温子仁氛围恐怖经典，腹语术人偶的诅咒', rating: '7.2', douban: 'https://movie.douban.com/subject/1866473/', poster: 'https://image.tmdb.org/t/p/w500/rvcUVdATIHKZt7BSSttUkKbeBXN.jpg' },
    { year: 2021, title_cn: '致命感应', title_en: 'The Medium', country: '泰国/韩国', desc: '伪纪录片式泰国恐怖，灵媒家族的附身恐惧', rating: '6.5', douban: 'https://movie.douban.com/subject/35373812/', poster: 'https://image.tmdb.org/t/p/w500/tWoSE8SH6XhgWKHIL3p0sj7lA3V.jpg' },
    { year: 2022, title_cn: '灵异咒', title_en: 'Incantation', country: '中国台湾', desc: '伪纪录片恐怖，打破第四面墙的诅咒体验', rating: '6.5', douban: 'https://movie.douban.com/subject/35471558/', poster: 'https://image.tmdb.org/t/p/w500/cWz28oGV3cSajWdziVQbqrYCmnX.jpg' },
    { year: 2024, title_cn: '危笑2', title_en: 'Smile 2', country: '美国', desc: '微笑诅咒升级版，流行歌手的崩溃之旅', rating: '6.7', douban: 'https://movie.douban.com/subject/36190805/', poster: 'https://image.tmdb.org/t/p/w500/aE85MnPIsSoSs3978Noo16BRsKN.jpg' },
  ],

  'erotic-cinema': [
    { year: 1984, title_cn: '白色罪恶', title_en: 'Crimes of Passion', country: '美国', desc: '情欲与道德的边界探索，争议性情色经典', rating: '6.0', poster: 'https://image.tmdb.org/t/p/w500/tstF6JMrZe75AdEAoPejwPrDfMA.jpg' },
    { year: 2013, title_cn: '女性瘾者：第一部', title_en: 'Nymphomaniac: Vol. I', country: '丹麦/德国/法国/比利时/英国', desc: '拉斯·冯·提尔的欲望编年史，坦诚到令人不安', rating: '6.8', douban: 'https://movie.douban.com/subject/11erta21/', poster: 'https://image.tmdb.org/t/p/w500/piikL8vRh3s1ysHGTIqaZpdjfNU.jpg' },
    { year: 2013, title_cn: '女性瘾者：第二部', title_en: 'Nymphomaniac: Vol. II', country: '丹麦/德国/法国/比利时/英国', desc: '更加黑暗的下半部，欲望的深渊与自我毁灭', rating: '6.5', douban: 'https://movie.douban.com/subject/25717843/', poster: 'https://image.tmdb.org/t/p/w500/iLUNqgNKuWn667kXCKztSxYbT3k.jpg' },
    { year: 2015, title_cn: '爱恋', title_en: 'Love', country: '法国/比利时', desc: '加斯帕·诺导演，3D实拍情欲关系的赤裸呈现', rating: '5.7', douban: 'https://movie.douban.com/subject/25852464/', poster: 'https://image.tmdb.org/t/p/w500/jx5rG229bzPzBgCXGslje75Y85x.jpg' },
    { year: 2018, title_cn: '杀死伊芙', title_en: 'Killing Eve', country: '英国/美国', desc: '女特工与女杀手的致命暧昧追逐，情欲张力拉满', rating: '8.5', douban: 'https://movie.douban.com/subject/26915erta/', poster: 'https://image.tmdb.org/t/p/w500/4wKhTVw8aGq5AZMa0Q1spERdi7n.jpg' },
    { year: 2022, title_cn: '关于约会的一切', title_en: 'All About Dating', country: '中国', desc: '都市男女的约会百态，暧昧关系与情感博弈', rating: '5.8' },
    { year: 2023, title_cn: '有希望的男人', title_en: 'A Man of Reason', country: '韩国', desc: '爱情与暴力交织，男性角色的情欲与救赎', rating: '5.9', douban: 'https://movie.douban.com/subject/36047673/', poster: 'https://image.tmdb.org/t/p/w500/ePwZs1oOh4pg8UZP8DuVZZeIn89.jpg' },
  ],

  'cult-collection': [
    { year: 1927, title_cn: '大都会', title_en: 'Metropolis', country: '德国', desc: 'Fritz Lang科幻鼻祖，地上天堂与地下奴隶的阶级寓言', rating: '9.0', poster: 'https://image.tmdb.org/t/p/w500/kr9wXRN23zLuWJIelahas1mtnYj.jpg' },
    { year: 1963, title_cn: '宇宙终点之旅', title_en: 'Ikarie XB 1', country: '捷克斯洛伐克', desc: '捷克经典科幻，星际飞船上的人性探索与未知恐惧', rating: '7.0', poster: 'https://image.tmdb.org/t/p/w500/svpzTXId4kH1pwn71e3ZOFUxd7L.jpg' },
    { year: 1968, title_cn: '魔法圣婴', title_en: "Rosemary's Baby", country: '美国', desc: '波兰斯基经典恐怖，怀孕妻子发现丈夫与邪教的交易', rating: '8.2', poster: 'https://image.tmdb.org/t/p/w500/uYgvlHceRFjAFbsNeMInYcLZLUb.jpg' },
    { year: 1971, title_cn: '发条橙', title_en: 'A Clockwork Orange', country: '英国/美国', desc: '库布里克经典，暴力少年被洗脑改造的反乌托邦寓言', rating: '8.5', poster: 'https://image.tmdb.org/t/p/w500/4sHeTAp65WrSSuc05nRBKddhBxO.jpg' },
    { year: 1972, title_cn: '魔屋', title_en: 'The Last House on the Left', country: '美国', desc: '韦斯·克雷文处女作，少女遭绑架后父母的血腥复仇', rating: '6.1', poster: 'https://image.tmdb.org/t/p/w500/9fNnBVooUmcMahgEw7AJ4piZnLX.jpg' },
    { year: 1972, title_cn: '索拉里斯', title_en: 'Solaris', country: '苏联', desc: '塔可夫斯基科幻杰作，外星海洋唤醒宇航员内心记忆', rating: '8.5', poster: 'https://image.tmdb.org/t/p/w500/pgqj7QoBPWFLLKtLEpPmFYFRMgB.jpg' },
    { year: 1972, title_cn: '墓地鬼话', title_en: 'Tales from the Crypt', country: '英国', desc: 'Amicus经典恐怖集锦，五个墓地访客的死亡预言', rating: '6.9', poster: 'https://image.tmdb.org/t/p/w500/vA3wsl2lfurU6UFVs0Hg0cZJDah.jpg' },
    { year: 1973, title_cn: '圣山', title_en: 'The Holy Mountain', country: '墨西哥/美国', desc: '佐杜洛夫斯基邪典巅峰，宗教、炼金术与意识觉醒', rating: '8.3', poster: 'https://image.tmdb.org/t/p/w500/mP5FGQbNjFkrjcZ6AVHrvokPRe5.jpg' },
    { year: 1973, title_cn: '修罗雪姬', title_en: 'Lady Snowblood', country: '日本', desc: '复仇女剑客雪中斩杀，杀死比尔的灵感来源', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/wkcbaqCoYEXDUnSQ6NTnB2C7H05.jpg' },
    { year: 1974, title_cn: '甜蜜电影', title_en: 'Sweet Movie', country: '法国/加拿大/西德', desc: '杜尚·马卡维耶夫的极端讽刺，资本主义与共产主义的荒诞碰撞', rating: '6.4', poster: 'https://image.tmdb.org/t/p/w500/64SaF3kOOaLPUVflDhXZLrB0xjt.jpg' },
    { year: 1974, title_cn: '鬼眼', title_en: 'Black Christmas', country: '加拿大', desc: '砍杀片鼻祖之一，圣诞夜女生宿舍的恐怖来电', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/ym0QcbrKNujzDyAU1IHGYUdRWub.jpg' },
    { year: 1975, title_cn: '洛基恐怖秀', title_en: 'The Rocky Horror Picture Show', country: '英国/美国', desc: '永恒的午夜cult经典，性别颠覆与摇滚狂欢', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/3pyE6ZqDbuJi7zrNzzQzcKTWdmN.jpg' },
    { year: 1977, title_cn: '第三类接触', title_en: 'Close Encounters of the Third Kind', country: '美国', desc: '斯皮尔伯格经典，普通人被外星信号召唤的神秘体验', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/gCWPB8cF82tqzrS9tvzcO6q6nyz.jpg' },
    { year: 1978, title_cn: '五毒', title_en: 'Five Deadly Venoms', country: '中国香港', desc: '邵氏经典武侠，五种毒门绝技的恩怨对决', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/z446TqbbOb7emtN1S8iOrwTHz7Y.jpg' },
    { year: 1980, title_cn: '邪', title_en: 'Bewitched', country: '中国香港', desc: '桂治洪邪典恐怖，降头术与邪灵附身', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/bUy2q8VDNnG0CZ58CHoZmb0vBYY.jpg' },
    { year: 1980, title_cn: '打蛇', title_en: 'Killer Snakes', country: '中国香港', desc: '邵氏cult经典，受辱青年以毒蛇复仇的极端故事', rating: '6.3', poster: 'https://image.tmdb.org/t/p/w500/hFQLaRvche2iDkpb8foSEWtCzzj.jpg' },
    { year: 1981, title_cn: '蛊', title_en: 'Bewitched', country: '中国香港', desc: '桂治洪蛊术恐怖，南洋黑巫术的血腥诅咒', rating: '6.5' },
    { year: 1981, title_cn: '时间劫匪', title_en: 'Time Bandits', country: '英国', desc: 'Terry Gilliam奇幻冒险，小男孩与矮人盗贼穿越时空', rating: '7.3', poster: 'https://image.tmdb.org/t/p/w500/4VZtpwdhHQSa4LUkvujyGAHb1hG.jpg' },
    { year: 1982, title_cn: '迷墙', title_en: 'Pink Floyd: The Wall', country: '英国', desc: 'Pink Floyd概念专辑影像化，摇滚巨星的精神崩溃与战争创伤', rating: '8.2', poster: 'https://image.tmdb.org/t/p/w500/aElHyIdF5jmctFGhlhhaPFsbBJC.jpg' },
    { year: 1984, title_cn: '一九八四', title_en: 'Nineteen Eighty-Four', country: '英国', desc: '奥威尔反乌托邦经典改编，极权监控下的思想犯罪', rating: '7.6', poster: 'https://image.tmdb.org/t/p/w500/hrdQlicxuyTg3zyVqq78EsA4Z6J.jpg' },
    { year: 1984, title_cn: '2010太空漫游', title_en: '2010: The Year We Make Contact', country: '美国', desc: '2001续集，美苏联合探索木星黑石碑的秘密', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/mfsvdukx4tCsUcqRGHtsEIWkWDK.jpg' },
    { year: 1985, title_cn: '妙想天开', title_en: 'Brazil', country: '英国', desc: 'Terry Gilliam反乌托邦杰作，官僚地狱中的白日梦逃脱', rating: '8.3', poster: 'https://image.tmdb.org/t/p/w500/aewan59WcFThBimkTVVoNf2o5Vb.jpg' },
    { year: 1985, title_cn: '活死人之日', title_en: 'Day of the Dead', country: '美国', desc: '罗梅罗丧尸三部曲终章，地下避难所中人性比丧尸更恐怖', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/bi7SO5F4VyyGQTlxQirbH1dwKzW.jpg' },
    { year: 1985, title_cn: '群尸屠城', title_en: 'Return of the Living Dead', country: '美国', desc: '欢乐血浆丧尸片，"要吃脑子"的经典由此而来', rating: '7.4', poster: 'https://image.tmdb.org/t/p/w500/oNsV9BychAe4Sk6xFKp558Rlpyz.jpg' },
    { year: 1987, title_cn: '鬼玩人2', title_en: 'Evil Dead II', country: '美国', desc: 'Sam Raimi邪典续作，Ash单手锯与丧尸的疯狂喜剧恐怖', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/4zqCKJVHUolGs6C5AZwAZqLWixW.jpg' },
    { year: 1988, title_cn: '风尘三女侠', title_en: 'She Shoots Straight', country: '中国香港', desc: '元彪+杨紫琼港产动作片，女警三姐妹的铁血执法', rating: '6.5', poster: 'https://image.tmdb.org/t/p/w500/7XumtdPXkoKZ2mXhSxyPcAPkGm.jpg' },
    { year: 1988, title_cn: '下水道美人鱼', title_en: 'Guinea Pig: Mermaid in a Manhole', country: '日本', desc: '豚鼠系列最有艺术感的一部，下水道中腐烂美人鱼的恐怖绘画', rating: '5.8', poster: 'https://image.tmdb.org/t/p/w500/vN2JcO9ZIn00DbuDbNjCWtqwqS6.jpg' },
    { year: 1988, title_cn: '银色星球', title_en: 'On the Silver Globe', country: '波兰', desc: '祖拉斯基未完成的科幻史诗，人类在外星球建立文明的疯狂寓言', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/4zzam82e6rCY2Ktm0fyRoseHhkh.jpg' },
    { year: 1988, title_cn: '黑太阳731', title_en: 'Men Behind the Sun', country: '中国香港', desc: '731部队人体实验的极端写实，华语禁片代表', rating: '6.6', poster: 'https://image.tmdb.org/t/p/w500/vTbOXA1gBIhuumN5CnRhxfDp9xY.jpg' },
    { year: 1989, title_cn: '圣血', title_en: 'Santa Sangre', country: '意大利/墨西哥', desc: '佐杜洛夫斯基的暗黑马戏团，断臂母亲操控儿子的双手杀人', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/6VTra0NR4ygRnq3bD922I4rU0Mq.jpg' },
    { year: 1990, title_cn: '活跳尸2', title_en: 'Bride of Re-Animator', country: '美国', desc: '疯狂医生继续复活实验，拼凑出完美新娘', rating: '6.5', poster: 'https://image.tmdb.org/t/p/w500/7t9PmI65umna8yq0BPU9YoKn62I.jpg' },
    { year: 1990, title_cn: '聊斋艳谈', title_en: 'Erotic Ghost Story', country: '中国香港', desc: '聊斋风月奇幻，狐仙与书生的香艳志怪', rating: '5.8', poster: 'https://image.tmdb.org/t/p/w500/fTUCwsxVoLFuodAtlL6aITP1B45.jpg' },
    { year: 1991, title_cn: '聊斋艳谈2', title_en: 'Erotic Ghost Story II', country: '中国香港', desc: '五通神作祟，更大胆的聊斋情色续篇', rating: '5.5', poster: 'https://image.tmdb.org/t/p/w500/ighnU4PYk0AQDW9qkD64E5p4hRd.jpg' },
    { year: 1991, title_cn: '力王', title_en: 'Riki-Oh: The Story of Ricky', country: '中国香港', desc: '拳穿肚皮的暴力cult经典，监狱血浆动作巅峰', rating: '7.0', poster: 'https://image.tmdb.org/t/p/w500/dzG0PAbBDLbJSYuv2SM2Mjxw2MH.jpg' },
    { year: 1991, title_cn: '裸体午餐', title_en: 'Naked Lunch', country: '加拿大/英国', desc: 'Cronenberg改编Burroughs，打字机变甲虫的致幻毒虫世界', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/u01kh5jKUWjhom76mguRqUgdvja.jpg' },
    { year: 1991, title_cn: '直到世界尽头', title_en: 'Until the End of the World', country: '德国/法国/澳大利亚', desc: '维姆·文德斯科幻公路片，横跨全球的追逐与梦境记录', rating: '7.0', poster: 'https://image.tmdb.org/t/p/w500/sDpYWgYkBlrVnpySXQNsxVvDAAG.jpg' },
    { year: 1992, title_cn: '鬼玩人3', title_en: 'Army of Darkness', country: '美国', desc: 'Ash穿越中世纪大战骷髅军团，cult喜剧动作巅峰', rating: '7.4', poster: 'https://image.tmdb.org/t/p/w500/xsgTuAtR2zSH8Umg3jWZcZjlDpe.jpg' },
    { year: 1992, title_cn: '妖兽都市', title_en: 'Wicked City', country: '中国香港', desc: '人妖混居的黑暗都市，徐克监制的成人奇幻动作', rating: '6.3', poster: 'https://image.tmdb.org/t/p/w500/560uq9mziscCktjYGYBc24q9z44.jpg' },
    { year: 1992, title_cn: '赤裸羔羊', title_en: 'Naked Killer', country: '中国香港', desc: '女杀手的情欲与杀戮，港产cult情色动作经典', rating: '6.5', poster: 'https://image.tmdb.org/t/p/w500/d9V3lIqF0fyQfMe4CUl86N0nQfJ.jpg' },
    { year: 1992, title_cn: '聊斋艳谈3', title_en: 'Erotic Ghost Story III', country: '中国香港', desc: '灯草和尚的荒唐奇遇，聊斋系列最癫狂一部', rating: '5.3', poster: 'https://image.tmdb.org/t/p/w500/2b1Y6NbZenY45DgC5CwncoLkpo.jpg' },
    { year: 1992, title_cn: '羔羊医生', title_en: 'Dr. Lamb', country: '中国香港', desc: '根据真实连环杀手改编，港产变态杀人犯的冷酷写实', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/qs9pkz5dz7SRXKTBPPTI7DwAYnf.jpg' },
    { year: 1993, title_cn: '人肉叉烧包', title_en: 'The Untold Story', country: '中国香港', desc: '黄秋生封神之作，澳门碎尸案的极端写实恐怖', rating: '7.2', poster: 'https://image.tmdb.org/t/p/w500/tQ7Ymo92AOXZFrMX5TBAfAdYECt.jpg' },
    { year: 1993, title_cn: '坏小子巴比', title_en: 'Bad Boy Bubby', country: '澳大利亚', desc: '被母亲囚禁35年的男人走入社会，荒诞残酷又温柔', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/fERbcofifizJmDt892lFcrIYhFh.jpg' },
    { year: 1993, title_cn: '画皮之阴阳法王', title_en: 'Painted Skin', country: '中国香港', desc: '林正英版画皮，阴阳法王与僵尸道长的对决', rating: '6.2', poster: 'https://image.tmdb.org/t/p/w500/hnGmNirm8DE7qIuB1qyDZTDFJuq.jpg' },
    { year: 1994, title_cn: '夜色', title_en: 'Color of Night', country: '美国', desc: 'Bruce Willis心理惊悚情色片，心理医生卷入谋杀谜团', rating: '5.4', poster: 'https://image.tmdb.org/t/p/w500/w1OBPkf3BxeC7543YzFwiKIwBFJ.jpg' },
    { year: 1995, title_cn: '南洋十大邪术', title_en: 'The Eternal Evil of Asia', country: '中国香港', desc: '泰国降头术的恐怖奇观，港产邪术cult经典', rating: '6.0', poster: 'https://image.tmdb.org/t/p/w500/2TOtVUmSUzXEpweCJzMxOKXMKYf.jpg' },
    { year: 1995, title_cn: '艳舞女郎', title_en: 'Showgirls', country: '美国', desc: 'Paul Verhoeven的拉斯维加斯脱衣舞娘野心记，烂到成邪典', rating: '5.0', poster: 'https://image.tmdb.org/t/p/w500/o4HT3Ap5c99W4FYpdXUtTvxGgPc.jpg' },
    { year: 1996, title_cn: '伊波拉病毒', title_en: 'Ebola Syndrome', country: '中国香港', desc: '黄秋生再演变态杀手，感染病毒后的疯狂屠杀', rating: '6.3', poster: 'https://image.tmdb.org/t/p/w500/3537kQNixMuzl9hS6WDY7J7v3nd.jpg' },
    { year: 1996, title_cn: '枕边禁书', title_en: 'The Pillow Book', country: '英国/荷兰/法国', desc: 'Peter Greenaway的身体书写美学，肉体即画布', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/haJOy4dOmy0nih5RH25FBuwVNH4.jpg' },
    { year: 1997, title_cn: '心慌方', title_en: 'Cube', country: '加拿大', desc: '困在致命机关迷宫的陌生人，密室逃脱恐怖鼻祖', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/x4BTjxdrOKC27FcSkBh8KPEgnum.jpg' },
    { year: 1998, title_cn: '六弦武士', title_en: 'Six-String Samurai', country: '美国', desc: '后启示录荒漠中弹吉他的武士，摇滚与武侠的荒诞混搭', rating: '6.5', poster: 'https://image.tmdb.org/t/p/w500/4Lo0pT1gnDAL4hTVMYLwpVWcqR1.jpg' },
    { year: 1998, title_cn: '移魂都市', title_en: 'Dark City', country: '美国/澳大利亚', desc: '黑暗城市中记忆被篡改的人们，视觉风格影响了黑客帝国', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/tNPEGju4DpTdbhBphNmZoEi9Bd3.jpg' },
    { year: 1999, title_cn: '波拉X', title_en: 'Pola X', country: '法国/德国/日本', desc: 'Leos Carax的黑暗情欲文学改编，身份崩塌与乱伦禁忌', rating: '6.2', poster: 'https://image.tmdb.org/t/p/w500/gTmZlEoH03sNtaNeYbboB7vgn5j.jpg' },
    { year: 2000, title_cn: '透明人', title_en: 'Hollow Man', country: '美国', desc: 'Paul Verhoeven的隐形人，透明带来的权力腐化与暴行', rating: '6.0', poster: 'https://image.tmdb.org/t/p/w500/sd3qUIv5uoP2oTbqv66CzXSPjKG.jpg' },
    { year: 2000, title_cn: '火星任务', title_en: 'Mission to Mars', country: '美国', desc: '德·帕尔玛的火星科幻，致敬2001的太空探索悲剧', rating: '6.0', poster: 'https://image.tmdb.org/t/p/w500/cTKWoBpN5Gvi0vpMb9mLtYlwXqT.jpg' },
    { year: 2001, title_cn: '买凶拍人', title_en: 'You Shoot, I Shoot', country: '中国香港', desc: '彭浩翔黑色幽默处女作，杀手与导演的荒诞合作', rating: '7.4', poster: 'https://image.tmdb.org/t/p/w500/c19P4K4hRhuCMlQoQuaadi8EOH4.jpg' },
    { year: 2002, title_cn: '不可撤销', title_en: 'Irréversible', country: '法国', desc: '加斯帕·诺的倒叙暴力，9分钟长镜头的极端体验', rating: '7.5', poster: 'https://image.tmdb.org/t/p/w500/rxeDxo8FvZpLu6iplNpxdtAVnfu.jpg' },
    { year: 2002, title_cn: '少数派报告', title_en: 'Minority Report', country: '美国', desc: '斯皮尔伯格改编PKD，预知犯罪的伦理困境', rating: '7.8', poster: 'https://image.tmdb.org/t/p/w500/ccqpHq5tk5W4ymbSbuoy4uYOxFI.jpg' },
    { year: 2002, title_cn: '时间机器', title_en: 'The Time Machine', country: '美国', desc: 'H.G.Wells经典重拍，为救爱人穿越80万年', rating: '6.3', poster: 'https://image.tmdb.org/t/p/w500/iYayQahkghlbAsfOQX8b5eBzGVy.jpg' },
    { year: 2002, title_cn: '感官45度', title_en: "Senso '45", country: '意大利', desc: 'Tinto Brass情色战争片，二战末期的背叛与欲望', rating: '4.8', poster: 'https://image.tmdb.org/t/p/w500/Cb8n2cAwssBCApYjwYbz67S6P0.jpg' },
    { year: 2005, title_cn: '罪恶之城', title_en: 'Sin City', country: '美国', desc: '罗德里格兹+弗兰克·米勒，黑白暴力漫画美学的极致', rating: '8.0', poster: 'https://image.tmdb.org/t/p/w500/i66G50wATMmPrvpP95f0XP6ZdVS.jpg' },
    { year: 2006, title_cn: '怒火攻心', title_en: 'Crank', country: '美国', desc: 'Jason Statham必须保持肾上腺素飙升否则心脏停跳', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/bbGOV9lES80el46Hj4GLj5zY25F.jpg' },
    { year: 2007, title_cn: '刑房', title_en: 'Grindhouse', country: '美国', desc: '塔伦蒂诺+罗德里格兹致敬B级片的双片联映', rating: '7.6', poster: 'https://image.tmdb.org/t/p/w500/tvMBwJlmQTIQf5EBjHzzyE9tjcN.jpg' },
    { year: 2008, title_cn: '金瓶梅', title_en: 'The Forbidden Legend: Sex & Chopsticks', country: '中国香港', desc: '经典情色文学改编，西门庆与潘金莲的欲望纠葛', rating: '4.5', poster: 'https://image.tmdb.org/t/p/w500/sc9LlvsdofSmImbodqrgmK774EA.jpg' },
    { year: 2008, title_cn: '真实魔鬼游戏', title_en: 'The Chasing World', country: '日本', desc: '被选中的人成为猎杀目标的死亡游戏，日式荒诞恐怖', rating: '5.5', poster: 'https://image.tmdb.org/t/p/w500/6pEF9GHI8wnXxRll2UvuedVVvXZ.jpg' },
    { year: 2009, title_cn: '杀人不分左右', title_en: 'The Last House on the Left', country: '美国', desc: '韦斯·克雷文经典翻拍，父母为女复仇的极端暴力', rating: '6.5', poster: 'https://image.tmdb.org/t/p/w500/2Y35XCUS8U8vC8vs0HDEVkPu1BM.jpg' },
    { year: 2009, title_cn: '金瓶梅2', title_en: 'The Forbidden Legend: Sex & Chopsticks 2', country: '中国香港', desc: '续集延续情色古装路线，更加大胆的欲望描写', rating: '4.2' },
    { year: 2010, title_cn: '塞尔维亚电影', title_en: 'A Serbian Film', country: '塞尔维亚', desc: '全球公认最具争议禁片，一个色情演员的终极噩梦', rating: '5.5', poster: 'https://image.tmdb.org/t/p/w500/cToUzXZ9AcUylfIt8vnXhiy6Y9m.jpg' },
    { year: 2010, title_cn: '维多利亚一号', title_en: 'Dream Home', country: '中国香港', desc: '何超仪主演，为买房不惜连环杀人的黑色讽刺', rating: '6.5', poster: 'https://image.tmdb.org/t/p/w500/edY2IRaCGEKuJstuLLJ9MQNAYKX.jpg' },
    { year: 2012, title_cn: '死亡寿司', title_en: 'Dead Sushi', country: '日本', desc: '井口升的变态喜剧恐怖，寿司变成杀人怪物', rating: '5.5', poster: 'https://image.tmdb.org/t/p/w500/6OemZ6GIjrq5L4WqCA0nsoIQeYM.jpg' },
    { year: 2013, title_cn: '鬼玩人4', title_en: 'Evil Dead', country: '美国', desc: '经典重启，山间小屋的恶灵复活升级版', rating: '6.8', poster: 'https://image.tmdb.org/t/p/w500/1gDV0Lm9y8ufIKzyf0h0GBgb9Zj.jpg' },
    { year: 2014, title_cn: '罪恶之城2', title_en: 'Sin City: A Dame to Kill For', country: '美国', desc: '黑白暴力美学续篇，罪恶都市的新故事', rating: '6.3', poster: 'https://image.tmdb.org/t/p/w500/50kALxDX4mmzIRljbNbPY0u4cie.jpg' },
    { year: 2018, title_cn: '曼蒂', title_en: 'Mandy', country: '美国/比利时', desc: '尼古拉斯·凯奇的迷幻复仇，霓虹地狱美学的极致暴力', rating: '7.0', poster: 'https://image.tmdb.org/t/p/w500/m0yf7J7HsKeK6E81SMRcX8vx6mH.jpg' },
    { year: 1985, title_cn: '豚鼠之恶魔实验', title_en: 'Guinea Pig: Devil\'s Experiment', country: '日本', desc: '豚鼠系列开山之作，纯粹的虐待影像实验', rating: '4.5', poster: 'https://image.tmdb.org/t/p/w500/gyloAdASwFB0Ksm9Ky9xHLYsgZk.jpg' },
    { year: 1985, title_cn: '豚鼠之血肉之花', title_en: 'Guinea Pig: Flower of Flesh and Blood', country: '日本', desc: '豚鼠系列最臭名昭著的一部，伪纪录片式肢解', rating: '4.2', poster: 'https://image.tmdb.org/t/p/w500/hV4KI3AyknlfGIaVyMq7p66Tc3X.jpg' },
    { year: 1986, title_cn: '豚鼠之他不会死', title_en: 'Guinea Pig: He Never Dies', country: '日本', desc: '豚鼠系列的黑色幽默转向，自残却死不了的男人', rating: '5.0', poster: 'https://image.tmdb.org/t/p/w500/fj6rt8lEG3M9IZmapjl313RiyNT.jpg' },
    { year: 1986, title_cn: '豚鼠之恶魔女医生', title_en: 'Guinea Pig: Devil Woman Doctor', country: '日本', desc: '豚鼠系列最荒诞的一部，女医生的诡异人体实验', rating: '4.0', poster: 'https://image.tmdb.org/t/p/w500/vmoBVHB2vn9FG6glO3cvFehupn3.jpg' },
    { year: 1988, title_cn: '豚鼠之圣母机器人', title_en: 'Guinea Pig: Android of Notre Dame', country: '日本', desc: '豚鼠系列科幻向，为救妹妹制造人造人的疯狂科学家', rating: '4.5', poster: 'https://image.tmdb.org/t/p/w500/ij1OI6I9pJK8kBxSRlMlHknHdkO.jpg' },
    { year: 1975, title_cn: '女集中营', title_en: 'Ilsa: She Wolf of the SS', country: '加拿大/西德', desc: '纳粹剥削电影代表作，集中营女指挥官的残酷实验', rating: '4.5', poster: 'https://image.tmdb.org/t/p/w500/tXTxGZkQs6e05oWarMpJ9gnIC8d.jpg' },
    { year: 1990, title_cn: '血恋', title_en: 'A Chinese Ghost Story II', country: '中国香港', desc: '港产奇幻恐怖情色，鬼魅与人间的纠缠', rating: '5.5' },
    { year: 1993, title_cn: '怪谈协会', title_en: 'Tales from the Dark Side', country: '中国香港', desc: '港产恐怖短片集锦，都市怪谈的惊悚合辑', rating: '5.8' },
    { year: 2010, title_cn: '五路追杀令2', title_en: "Smokin' Aces 2: Assassins' Ball", country: '美国', desc: '杀手集结的暴力狂欢，B级动作片的痛快', rating: '5.0', poster: 'https://image.tmdb.org/t/p/w500/4t8mSYKtaXGvaro48ci0ZMzVvbe.jpg' }
  ]
}
